### ISSUE TITLE
HTTP Status 500 – Internal Server Error when deleting tournaments

### ISSUE THREAD

**Issue by TakumaFujiwara** [NRequa/EE461L_Jaguar_SSBracket#10]
Deleting a tournament returns a HTML response that says we are getting an internal server error. Using MySQL workbench, I can see that the tournaments are actually deleted. The onDelete in the tournament and user model might be causing the problem.

**Comment by up1007** [comment]
We debugged the DELETE. For tournaments we eliminated all underscores and infinite loops by adding jsonignore to the parameter in user that stored in tournaments.
